export const PRACTICE_TECHNIQUES = [
  {
    id: 'boxing_strikes_jab_001',
    discipline: 'Boxing',
    category: 'Strikes',
    name: 'Jab',
    description: 'Straight lead-hand punch',
    level: 'Beginner',
    duration: '20-30 sec',
    videoUrl: '',
    cues: ['Hands high', 'Step with the jab', 'Return to guard'],
    mistakes: ['Dropping rear hand', 'Reaching too far', 'Chin up'],
    next: 'Cross',
    locked: true,
    active: true,
  },
  {
    id: 'boxing_strikes_cross_001',
    discipline: 'Boxing',
    category: 'Strikes',
    name: 'Cross',
    description: 'Rear-hand power punch',
    level: 'Beginner',
    duration: '20-30 sec',
    videoUrl: '',
    cues: ['Rotate the hip', 'Drive off the back foot', 'Tuck the chin'],
    mistakes: ['Telegraphing', 'Leaning forward', 'Leaving guard open'],
    next: 'Lead Hook',
    locked: true,
    active: true,
  },
  {
    id: 'kickboxing_strikes_teep_001',
    discipline: 'Kickboxing',
    category: 'Strikes',
    name: 'Lead Teep',
    description: 'Lead-leg front push kick',
    level: 'Beginner',
    duration: '20-30 sec',
    videoUrl: '',
    cues: ['Chamber knee', 'Push with heel', 'Return fast'],
    mistakes: ['Skipping chamber', 'Pushing too low', 'Landing off-balance'],
    next: 'Rear Teep',
    locked: true,
    active: true,
  },
  {
    id: 'muaythai_strikes_roundhouse_001',
    discipline: 'Muay Thai',
    category: 'Strikes',
    name: 'Roundhouse',
    description: 'Full-rotation shin kick',
    level: 'Beginner',
    duration: '20-30 sec',
    videoUrl: '',
    cues: ['Rotate hips', 'Strike with shin', 'Return to stance'],
    mistakes: ['No pivot', 'Kicking with foot', 'Slow return'],
    next: 'Teep',
    locked: true,
    active: true,
  },
  {
    id: 'mma_defense_sprawl_001',
    discipline: 'MMA',
    category: 'Defense',
    name: 'Sprawl',
    description: 'Hip-heavy takedown defense movement',
    level: 'Beginner',
    duration: '20-30 sec',
    videoUrl: '',
    cues: ['Hips heavy', 'Chest pressure', 'Fast reset'],
    mistakes: ['Hands too low', 'Hips too high', 'Slow recovery'],
    next: 'Level Change',
    locked: true,
    active: true,
  },
];
