// Combat Conditioning Drills data
// Auto-generated from Training_Mode_MVP_Database_Merged_-_Combat_Conditioning.csv

export const COMBAT_CONDITIONING_DRILLS = [
  {
    id: 'combat_0001',
    name: 'Cable Flyes (High/Low/Cross Over)',
    style: 'General',
    equipment: 'Cable',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Cable Flyes (High/Low/Cross Over)',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Cable Flyes (High/Low/Cross Over). Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0002',
    name: 'Cross-Body Push-Ups',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Cross-Body Push-Ups',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Cross-Body Push-Ups. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0003',
    name: 'Kettlebell Alternating Floor Press',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Kettlebell Alternating Floor Press',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds punching endurance, guard strength, and upper-body power.',
    voiceIntro: 'Kettlebell Alternating Floor Press. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0004',
    name: 'Kettlebell Floor Press',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Kettlebell Floor Press',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds punching endurance, guard strength, and upper-body power.',
    voiceIntro: 'Kettlebell Floor Press. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0005',
    name: 'Side Kick Push-Ups',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Side Kick Push-Ups',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Side Kick Push-Ups. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0006',
    name: 'Staggered Push-Ups (one leg lunged back)',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Staggered Push-Ups (one leg lunged back)',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds punching endurance, guard strength, and upper-body power.',
    voiceIntro: 'Staggered Push-Ups (one leg lunged back). Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0007',
    name: 'Barbell Lateral Lunges',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Barbell Lateral Lunges',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Supports posture, clinch control, pulling strength, and guard recovery.',
    voiceIntro: 'Barbell Lateral Lunges. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0008',
    name: 'Cable Kickbacks',
    style: 'General',
    equipment: 'Cable',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Cable Kickbacks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Cable Kickbacks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0009',
    name: 'Dumbbell Kickbacks',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Dumbbell Kickbacks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Dumbbell Kickbacks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0010',
    name: 'Kettlebell Renegade Rows',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Kettlebell Renegade Rows',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Supports posture, clinch control, pulling strength, and guard recovery.',
    voiceIntro: 'Kettlebell Renegade Rows. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0011',
    name: 'Resistance Band Kickbacks',
    style: 'General',
    equipment: 'Band',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Resistance Band Kickbacks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Resistance Band Kickbacks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0012',
    name: 'Single-Leg Deadlift to Lunge',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Single-Leg Deadlift to Lunge',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Supports posture, clinch control, pulling strength, and guard recovery.',
    voiceIntro: 'Single-Leg Deadlift to Lunge. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0013',
    name: 'Arm Circles',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Arm Circles',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds punching endurance, guard strength, and upper-body power.',
    voiceIntro: 'Arm Circles. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0014',
    name: 'Wall Ball Throws',
    style: 'General',
    equipment: 'Cardio',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Wall Ball Throws',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds punching endurance, guard strength, and upper-body power.',
    voiceIntro: 'Wall Ball Throws. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0015',
    name: 'Cross Body Hammer Curls',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Cross Body Hammer Curls',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Cross Body Hammer Curls. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0016',
    name: 'Jab-Cross Drill',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Jab-Cross Drill',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Jab-Cross Drill. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0017',
    name: 'Arnold Press (incorporates core for stabilization)',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Arnold Press (incorporates core for stabilization)',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Arnold Press (incorporates core for stabilization). Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0018',
    name: 'Barbell Landmine Rotations',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Barbell Landmine Rotations',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Barbell Landmine Rotations. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0019',
    name: 'Bicycle Crunches',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Bicycle Crunches',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Bicycle Crunches. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0020',
    name: 'Cable Crunches',
    style: 'General',
    equipment: 'Cable',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Cable Crunches',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Cable Crunches. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0021',
    name: 'Cable Oblique Pushdown',
    style: 'General',
    equipment: 'Cable',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Cable Oblique Pushdown',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Cable Oblique Pushdown. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0022',
    name: 'Cable Woodchoppers',
    style: 'General',
    equipment: 'Cable',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Cable Woodchoppers',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Cable Woodchoppers. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0023',
    name: 'Core/Cardio',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Core/Cardio',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Core/Cardio. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0024',
    name: 'Core/Cardio',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Core/Cardio',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Core/Cardio. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0025',
    name: 'Corkscrew',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Corkscrew',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Corkscrew. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0026',
    name: 'Cross-Body Mountain Climbers',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Cross-Body Mountain Climbers',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Cross-Body Mountain Climbers. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0027',
    name: 'Deadlift (core engagement for spinal support)',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Deadlift (core engagement for spinal support)',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Deadlift (core engagement for spinal support). Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0028',
    name: 'Dumbbell Side Bends',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Dumbbell Side Bends',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Dumbbell Side Bends. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0029',
    name: 'Dumbbell V-Sit Cross Jab',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Dumbbell V-Sit Cross Jab',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Dumbbell V-Sit Cross Jab. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0030',
    name: 'Dynamic Side Plank',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Dynamic Side Plank',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Dynamic Side Plank. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0031',
    name: 'Farmer\'s Walk (core stability under load)',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Farmer\'s Walk (core stability under load)',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Farmer\'s Walk (core stability under load). Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0032',
    name: 'Flutter Kicks',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Flutter Kicks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Flutter Kicks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0033',
    name: 'Heel Taps',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Heel Taps',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Heel Taps. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0034',
    name: 'High Knees',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'High Knees',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'High Knees. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0035',
    name: 'High Plank Leg Lifts',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'High Plank Leg Lifts',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'High Plank Leg Lifts. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0036',
    name: 'In and Out Abs',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'In and Out Abs',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'In and Out Abs. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0037',
    name: 'In and Outs',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'In and Outs',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'In and Outs. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0038',
    name: 'Ketlltebell Straight Arm Sit up',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Ketlltebell Straight Arm Sit up',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Ketlltebell Straight Arm Sit up. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0039',
    name: 'Kettlebell Bottoms Up Clean',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Kettlebell Bottoms Up Clean',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Kettlebell Bottoms Up Clean. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0040',
    name: 'Kettlebell Double Swing',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Kettlebell Double Swing',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Kettlebell Double Swing. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0041',
    name: 'Kettlebell Double Windmill',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Kettlebell Double Windmill',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Kettlebell Double Windmill. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0042',
    name: 'Kettlebell Get Up',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Kettlebell Get Up',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Kettlebell Get Up. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0043',
    name: 'Kettlebell Windmill',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Kettlebell Windmill',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Kettlebell Windmill. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0044',
    name: 'Knee Pull-Ins',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Knee Pull-Ins',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Knee Pull-Ins. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0045',
    name: 'Leg Raises',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Leg Raises',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Leg Raises. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0046',
    name: 'Lying Leg Lifts',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Lying Leg Lifts',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Lying Leg Lifts. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0047',
    name: 'Mountain Climbers',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Mountain Climbers',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Mountain Climbers. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0048',
    name: 'Oblique V-Ups',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Oblique V-Ups',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Oblique V-Ups. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0049',
    name: 'Overhead Dumbbell Extension (standing, engages core)',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Overhead Dumbbell Extension (standing, engages core)',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Overhead Dumbbell Extension (standing, engages core). Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0050',
    name: 'Pallof Press',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Pallof Press',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Pallof Press. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0051',
    name: 'Pendulum Legs',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Pendulum Legs',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Pendulum Legs. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0052',
    name: 'Plank Hip Dips',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Plank Hip Dips',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Plank Hip Dips. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0053',
    name: 'Plank Jacks',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Plank Jacks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Plank Jacks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0054',
    name: 'Plank Knee to Opposite Elbow',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Plank Knee to Opposite Elbow',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Plank Knee to Opposite Elbow. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0055',
    name: 'Plank Up-Downs',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Plank Up-Downs',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Plank Up-Downs. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0056',
    name: 'Plate Twist',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Plate Twist',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Plate Twist. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0057',
    name: 'Reverse Crunch with Twist',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Reverse Crunch with Twist',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Reverse Crunch with Twist. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0058',
    name: 'Reverse Crunches',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Reverse Crunches',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Reverse Crunches. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0059',
    name: 'Scissor Kicks',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Scissor Kicks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Scissor Kicks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0060',
    name: 'Scissor Kicks',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Scissor Kicks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Scissor Kicks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0061',
    name: 'Side Jackknife on Bench',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Side Jackknife on Bench',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Side Jackknife on Bench. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0062',
    name: 'Side Planks',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Side Planks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Side Planks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0063',
    name: 'Sit Up with KB on Chest',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Sit Up with KB on Chest',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Sit Up with KB on Chest. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0064',
    name: 'Sit-Ups',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Sit-Ups',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Sit-Ups. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0065',
    name: 'Squat (core stability)',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Squat (core stability)',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Squat (core stability). Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0066',
    name: 'Stability Ball Russian Twists',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Stability Ball Russian Twists',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Stability Ball Russian Twists. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0067',
    name: 'Star Planks',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Star Planks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Star Planks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0068',
    name: 'T-Bar Row with Twist',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'T-Bar Row with Twist',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'T-Bar Row with Twist. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0069',
    name: 'Tuck Jumps',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Tuck Jumps',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Tuck Jumps. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0070',
    name: 'Volume Punching',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 75,
    movements: 'Volume Punching',
    coachNote: 'Brace your core and keep your spine stable.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Volume Punching. Brace your core and keep your spine stable.',
    active: true,
  },
  {
    id: 'combat_0071',
    name: 'Weighted Pilates Scissors',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Weighted Pilates Scissors',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Weighted Pilates Scissors. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0072',
    name: 'Weighted Reverse Crunches',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Weighted Reverse Crunches',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Weighted Reverse Crunches. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0073',
    name: 'Weighted Russian Twists',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Weighted Russian Twists',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'Weighted Russian Twists. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0074',
    name: 'toe Touch',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'toe Touch',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds rotational control, bracing, and transfer of striking power.',
    voiceIntro: 'toe Touch. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0075',
    name: 'Alternating Reverse Lunge with Hop',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Alternating Reverse Lunge with Hop',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Alternating Reverse Lunge with Hop. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0076',
    name: 'Barbell Forward Lunges',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Barbell Forward Lunges',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Barbell Forward Lunges. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0077',
    name: 'Barbell Reverse Lunges',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Barbell Reverse Lunges',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Barbell Reverse Lunges. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0078',
    name: 'Barbell Walking Lunges',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Barbell Walking Lunges',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Barbell Walking Lunges. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0079',
    name: 'Bike Sprints',
    style: 'General',
    equipment: 'Machine',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Bike Sprints',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Bike Sprints. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0080',
    name: 'Box Jumps + Burpees',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Advanced',
    rounds: 3,
    workSeconds: 60,
    restSeconds: 90,
    movements: 'Box Jumps + Burpees',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Box Jumps + Burpees. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0081',
    name: 'Broad Jumps',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Broad Jumps',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Broad Jumps. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0082',
    name: 'Burpees + Pistol Squats',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Burpees + Pistol Squats',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Burpees + Pistol Squats. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0083',
    name: 'Butt Kicks',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Butt Kicks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Butt Kicks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0084',
    name: 'Dynamic Lunge (moving in and out quickly)',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Dynamic Lunge (moving in and out quickly)',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Dynamic Lunge (moving in and out quickly). Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0085',
    name: 'Elliptical Sprint',
    style: 'General',
    equipment: 'Machine',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Elliptical Sprint',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Elliptical Sprint. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0086',
    name: 'Endurance Punching',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 75,
    movements: 'Endurance Punching',
    coachNote: 'Stay balanced and drive through each rep with control.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Endurance Punching. Stay balanced and drive through each rep with control.',
    active: true,
  },
  {
    id: 'combat_0087',
    name: 'Fast Feet',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Fast Feet',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Fast Feet. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0088',
    name: 'Fast Feet + Sprawls',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Fast Feet + Sprawls',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Fast Feet + Sprawls. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0089',
    name: 'Frog Jumps',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Frog Jumps',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Frog Jumps. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0090',
    name: 'High Knees',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'High Knees',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'High Knees. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0091',
    name: 'Incline Walk',
    style: 'General',
    equipment: 'Machine',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Incline Walk',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Incline Walk. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0092',
    name: 'Jump Lunges',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Jump Lunges',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Jump Lunges. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0093',
    name: 'Kettlebell Goblet Squat',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Kettlebell Goblet Squat',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Kettlebell Goblet Squat. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0094',
    name: 'Kettlebell Single Clean',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Kettlebell Single Clean',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Kettlebell Single Clean. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0095',
    name: 'Kettlebell Single Overhead Squat',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Kettlebell Single Overhead Squat',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Kettlebell Single Overhead Squat. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0096',
    name: 'Kettlebell Single Swing',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Kettlebell Single Swing',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Kettlebell Single Swing. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0097',
    name: 'Kettlebell Snatch',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Kettlebell Snatch',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Kettlebell Snatch. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0098',
    name: 'Kick-Switch Drill',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Kick-Switch Drill',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Kick-Switch Drill. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0099',
    name: 'Lunge to Step-Up',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Lunge to Step-Up',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Lunge to Step-Up. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0100',
    name: 'Mountain Climber to Lunge',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Mountain Climber to Lunge',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Mountain Climber to Lunge. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0101',
    name: 'Plyometric Split Squat Jump',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Plyometric Split Squat Jump',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Plyometric Split Squat Jump. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0102',
    name: 'Racked Front Lunge',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Racked Front Lunge',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Racked Front Lunge. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0103',
    name: 'Racked Reverse Lunge',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Racked Reverse Lunge',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Racked Reverse Lunge. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0104',
    name: 'Single-Leg Box Squats',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Single-Leg Box Squats',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Single-Leg Box Squats. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0105',
    name: 'Skater Lunges',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Skater Lunges',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Skater Lunges. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0106',
    name: 'Squat Pulses',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Squat Pulses',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Squat Pulses. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0107',
    name: 'Squat to Toe Touch',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Squat to Toe Touch',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Squat to Toe Touch. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0108',
    name: 'Static Lunge',
    style: 'General',
    equipment: 'Kettlebell',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Static Lunge',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Static Lunge. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0109',
    name: 'Step Touch',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Step Touch',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Step Touch. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0110',
    name: 'Sumo Squats',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Sumo Squats',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Sumo Squats. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0111',
    name: 'Toe Taps',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Toe Taps',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Toe Taps. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0112',
    name: 'Treadmill Run + Sprint',
    style: 'General',
    equipment: 'Machine',
    difficulty: 'Hard',
    rounds: 3,
    workSeconds: 45,
    restSeconds: 75,
    movements: 'Treadmill Run + Sprint',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Treadmill Run + Sprint. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0113',
    name: 'Upper Body/Cardio',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Upper Body/Cardio',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds base, footwork, level changes, and explosive movement.',
    voiceIntro: 'Upper Body/Cardio. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0114',
    name: 'Volume Punching',
    style: 'General',
    equipment: 'Weighted',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 75,
    movements: 'Volume Punching',
    coachNote: 'Stay balanced and drive through each rep with control.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Volume Punching. Stay balanced and drive through each rep with control.',
    active: true,
  },
  {
    id: 'combat_0115',
    name: 'Bike Sprints',
    style: 'General',
    equipment: 'Machine',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Bike Sprints',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds fight pace, conditioning, and round-by-round recovery.',
    voiceIntro: 'Bike Sprints. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0116',
    name: 'Box Jumps + Burpees',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Box Jumps + Burpees',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds fight pace, conditioning, and round-by-round recovery.',
    voiceIntro: 'Box Jumps + Burpees. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0117',
    name: 'Burpees',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Burpees',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds fight pace, conditioning, and round-by-round recovery.',
    voiceIntro: 'Burpees. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0118',
    name: 'Burpees + Pistol Squats',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Burpees + Pistol Squats',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds fight pace, conditioning, and round-by-round recovery.',
    voiceIntro: 'Burpees + Pistol Squats. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0119',
    name: 'Burpees + Speed Combos',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Normal',
    rounds: 3,
    workSeconds: 40,
    restSeconds: 60,
    movements: 'Burpees + Speed Combos',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Builds fight pace, conditioning, and round-by-round recovery.',
    voiceIntro: 'Burpees + Speed Combos. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  },
  {
    id: 'combat_0120',
    name: 'Butt Kicks',
    style: 'General',
    equipment: 'Bodyweight',
    difficulty: 'Easy',
    rounds: 3,
    workSeconds: 30,
    restSeconds: 45,
    movements: 'Butt Kicks',
    coachNote: 'Keep a steady pace and stay sharp through the full interval.',
    combatGoal: 'Direct combat-conditioning drill for rhythm, reaction, and fight endurance.',
    voiceIntro: 'Butt Kicks. Keep a steady pace and stay sharp through the full interval.',
    active: true,
  }
];
