// The staples.
//
// The imported exercise library (fitModeExerciseData) stopped partway through
// an alphabetical export: 74 of its 134 entries start with A or B, and it has
// no plain Push-Up, Pull-Up, Squat, Lunge, Plank, Row, Bench Press or
// Deadlift at all. Beta found the builder dealing Aztec and Archer push-ups to
// a Normal athlete every single time because those were the only push-ups it
// owned. This file is the missing middle of that library: the movements a
// coach would actually programme first, in the same shape so the generator,
// the info sheet, the weight log and the demo art treat them like any other
// entry.
//
// Equipment vocabulary: Bodyweight · Weighted (dumbbells, a bar, kettlebells)
// · Band. Nothing here needs a cable stack or a machine.

const idOf = (muscle, name) => `${muscle.toLowerCase().replace(/\s+/g, '_')}_${name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '')}_core`;

// ex(name, muscle, secondary, equipment, difficulty, movement, cue, carry, opts)
// opts: hold (seconds) for timed work · reps (string) · rest · tempo · style
function ex(name, primaryMuscle, secondaryMuscles, equipment, difficulty, movementType, coachNote, combatCarryover, opts = {}) {
  const hold = opts.hold || null;
  const bodyMapRegion = ['Biceps', 'Triceps'].includes(primaryMuscle) ? 'Arms'
    : ['Quads', 'Hamstrings', 'Calves'].includes(primaryMuscle) ? 'Legs' : primaryMuscle;
  return {
    id: idOf(primaryMuscle, name),
    name,
    primaryMuscle,
    secondaryMuscles,
    equipment,
    difficulty,
    movementType,
    trainingStyle: opts.style || (hold ? 'Endurance' : 'Strength'),
    sets: 3,
    reps: hold ? `${hold}s` : (opts.reps || (equipment === 'Bodyweight' ? '10-15' : '8-12')),
    durationSeconds: hold,
    restSeconds: opts.rest || (hold ? 30 : 60),
    coachNote,
    voiceIntro: `${name}. ${coachNote}`,
    voiceCountingType: hold ? 'timed_hold' : 'rep_count',
    voiceCadenceSeconds: hold ? null : 1.5,
    tempo: opts.tempo || (hold ? null : '2 down, control, strong finish'),
    combatCarryover,
    cardioFinisher: false,
    bodyMapRegion,
    videoUrl: '',
    previewTip: coachNote,
    active: true,
  };
}

export const FIT_MODE_CORE_EXERCISES = [
  // ── Chest ────────────────────────────────────────────────────────────
  ex('Push-Ups', 'Chest', ['Triceps', 'Shoulders'], 'Bodyweight', 'Normal', 'Compound',
    'Hands under the shoulders, body in one line, chest to the floor and press away.', 'The base of every punch: chest, shoulders and triceps working as one.'),
  ex('Wide Push-Ups', 'Chest', ['Shoulders'], 'Bodyweight', 'Normal', 'Compound',
    'Hands wider than the shoulders, elbows out at forty-five degrees, lower with control.', 'Chest width for a heavier cross.'),
  ex('Diamond Push-Ups', 'Chest', ['Triceps'], 'Bodyweight', 'Hard', 'Compound',
    'Thumbs and index fingers touching under the chest, elbows tucked, press all the way up.', 'Triceps lockout — the snap at the end of a straight punch.'),
  ex('Decline Push-Ups', 'Chest', ['Shoulders', 'Triceps'], 'Bodyweight', 'Hard', 'Compound',
    'Feet on a step, hands on the floor, chin toward the ground, press up strong.', 'Upper chest and shoulders for punching up at a taller opponent.'),
  ex('Plyo Push-Ups', 'Chest', ['Triceps', 'Shoulders'], 'Bodyweight', 'Hard', 'Compound',
    'Drop fast, explode up so the hands leave the floor, land soft and go again.', 'Hand speed and explosive pressing power.', { reps: '6-10', rest: 75 }),
  ex('Dumbbell Bench Press', 'Chest', ['Triceps', 'Shoulders'], 'Weighted', 'Normal', 'Compound',
    'Lie back, dumbbells over the chest, lower to the sides of the chest and press together at the top.', 'Pressing power behind the cross.'),
  ex('Incline Dumbbell Press', 'Chest', ['Shoulders', 'Triceps'], 'Weighted', 'Normal', 'Compound',
    'Bench at thirty degrees, press up and slightly back, squeeze at the top.', 'Upper chest for punching upward and clinch pressing.'),
  ex('Dumbbell Flyes', 'Chest', ['Shoulders'], 'Weighted', 'Normal', 'Isolation',
    'Slight bend in the elbows, open the arms wide, squeeze the dumbbells back together over the chest.', 'Chest control for hooks and clinch work.', { reps: '10-12' }),
  ex('Dumbbell Floor Press', 'Chest', ['Triceps'], 'Weighted', 'Easy', 'Compound',
    'Lie on the floor, elbows touch down each rep, press to lockout.', 'Safe pressing strength with no bench needed.'),
  ex('Dumbbell Pullover', 'Chest', ['Back', 'Triceps'], 'Weighted', 'Normal', 'Compound',
    'One dumbbell over the chest, arms nearly straight, lower it behind the head and pull it back over.', 'Opens the ribcage for breathing between rounds.', { reps: '10-12' }),

  // ── Back ─────────────────────────────────────────────────────────────
  ex('Pull-Ups', 'Back', ['Biceps', 'Shoulders'], 'Bodyweight', 'Hard', 'Compound',
    'Hang under the bar, body straight, pull until the chin clears it, lower all the way down.', 'Pulling strength for the clinch and for keeping a guard up.', { reps: '5-8', rest: 90 }),
  ex('Chin-Ups', 'Back', ['Biceps'], 'Bodyweight', 'Normal', 'Compound',
    'Palms facing you, pull the chest to the bar, lower slow.', 'Bicep and lat strength for pulling an opponent in.', { reps: '5-8', rest: 90 }),
  ex('Inverted Rows', 'Back', ['Biceps', 'Shoulders'], 'Bodyweight', 'Normal', 'Compound',
    'Hang under a bar or table edge, body straight, pull the chest to the bar and squeeze the shoulder blades.', 'Back strength that keeps the shoulders healthy under punching volume.'),
  ex('Superman Hold', 'Back', ['Glutes', 'Core'], 'Bodyweight', 'Easy', 'Isolation',
    'Face down, lift the arms and legs off the floor together and hold.', 'Lower-back endurance for a strong stance.', { hold: 30 }),
  ex('Reverse Snow Angels', 'Back', ['Shoulders'], 'Bodyweight', 'Easy', 'Isolation',
    'Face down, arms off the floor, sweep them from the hips to overhead and back, slow.', 'Rear shoulder health for a guard that never drops.', { reps: '10-12' }),
  ex('Dumbbell Bent-Over Rows', 'Back', ['Biceps', 'Shoulders'], 'Weighted', 'Normal', 'Compound',
    'Hinge at the hips, flat back, pull the dumbbells to the hips and squeeze.', 'The pull behind every clinch and every recovered guard.'),
  ex('Single-Arm Dumbbell Row', 'Back', ['Biceps'], 'Weighted', 'Normal', 'Compound',
    'One hand on the bench, pull the dumbbell to the hip, elbow close to the body.', 'Single-side pulling strength for grappling exchanges.'),
  ex('Barbell Rows', 'Back', ['Biceps', 'Hamstrings'], 'Weighted', 'Hard', 'Compound',
    'Hinge to about forty-five degrees, pull the bar to the lower chest, lower under control.', 'Heavy pulling strength for the whole posterior chain.', { reps: '6-10', rest: 90 }),
  ex('Deadlifts', 'Back', ['Hamstrings', 'Glutes'], 'Weighted', 'Hard', 'Compound',
    'Bar over the mid-foot, flat back, push the floor away and stand tall, then lower with control.', 'Total-body strength that shows up in every takedown defence.', { reps: '5-8', rest: 120 }),
  ex('Dumbbell Deadlifts', 'Back', ['Hamstrings', 'Glutes'], 'Weighted', 'Normal', 'Compound',
    'Dumbbells at the sides, hinge with a flat back to mid-shin, drive up through the heels.', 'Hip and back strength for a rooted stance.', { reps: '8-10', rest: 90 }),
  ex('Renegade Rows', 'Back', ['Core', 'Shoulders'], 'Weighted', 'Hard', 'Compound',
    'Plank on two dumbbells, row one to the hip without letting the hips twist, then the other.', 'Anti-rotation core strength for absorbing body shots.', { reps: '6-8' }),
  ex('Band Pull-Aparts', 'Back', ['Shoulders'], 'Band', 'Easy', 'Isolation',
    'Arms straight in front, pull the band apart until it touches the chest, control it back.', 'Shoulder health for high-volume punching.', { reps: '15-20', rest: 30 }),
  ex('Band Lat Pulldown', 'Back', ['Biceps'], 'Band', 'Normal', 'Compound',
    'Band anchored high, pull the handles to the chest with the elbows driving down.', 'Lat strength for the clinch when there is no bar.', { reps: '12-15' }),

  // ── Shoulders ────────────────────────────────────────────────────────
  ex('Pike Push-Ups', 'Shoulders', ['Triceps', 'Chest'], 'Bodyweight', 'Normal', 'Compound',
    'Hips high in an upside-down V, lower the head toward the floor, press back up.', 'Overhead pressing strength for the guard and the clinch.', { reps: '8-12' }),
  ex('Shoulder Taps', 'Shoulders', ['Core'], 'Bodyweight', 'Easy', 'Isolation',
    'High plank, tap the opposite shoulder without letting the hips rock.', 'Shoulder stability under a guard that is always up.', { reps: '16-20', rest: 30 }),
  ex('Handstand Hold', 'Shoulders', ['Core', 'Triceps'], 'Bodyweight', 'Hard', 'Isolation',
    'Kick up against a wall, arms locked, squeeze everything and hold.', 'Overhead stability and a strong lockout.', { hold: 30, rest: 60 }),
  ex('Plank to Down Dog', 'Shoulders', ['Core', 'Hamstrings'], 'Bodyweight', 'Easy', 'Compound',
    'From a plank, push the hips up and back, then return to the plank, slow.', 'Shoulder mobility for a loose, fast guard.', { reps: '10-12', rest: 30 }),
  ex('Dumbbell Shoulder Press', 'Shoulders', ['Triceps'], 'Weighted', 'Normal', 'Compound',
    'Dumbbells at the shoulders, press overhead to lockout, lower under control.', 'The overhead strength behind uppercuts and framing.'),
  ex('Lateral Raises', 'Shoulders', [], 'Weighted', 'Normal', 'Isolation',
    'Slight bend in the elbows, raise the dumbbells to shoulder height, lower slow.', 'Shoulder endurance for a guard that lasts twelve rounds.', { reps: '12-15', rest: 45 }),
  ex('Front Raises', 'Shoulders', [], 'Weighted', 'Normal', 'Isolation',
    'Raise the dumbbells straight in front to eye level, one at a time or together.', 'Front shoulder strength for the jab.', { reps: '10-12', rest: 45 }),
  ex('Rear Delt Flyes', 'Shoulders', ['Back'], 'Weighted', 'Normal', 'Isolation',
    'Hinge forward, arms hanging, raise the dumbbells out to the sides and squeeze the shoulder blades.', 'Rear shoulder balance so punching volume never wrecks the joint.', { reps: '12-15', rest: 45 }),
  ex('Dumbbell Upright Rows', 'Shoulders', ['Back', 'Biceps'], 'Weighted', 'Normal', 'Compound',
    'Dumbbells in front of the thighs, pull them up along the body to chest height, elbows leading.', 'Trap and shoulder strength for the clinch.', { reps: '10-12' }),
  ex('Dumbbell Shrugs', 'Shoulders', ['Back'], 'Weighted', 'Easy', 'Isolation',
    'Heavy dumbbells at the sides, shrug the shoulders straight up to the ears, pause, lower.', 'Neck and trap armour against head shots.', { reps: '12-15', rest: 45 }),

  // ── Biceps ───────────────────────────────────────────────────────────
  ex('Dumbbell Curls', 'Biceps', [], 'Weighted', 'Normal', 'Isolation',
    'Elbows pinned at the sides, curl to the shoulder, lower slow.', 'Arm strength for hooks and for holding a clinch.', { reps: '10-12', rest: 45 }),
  ex('Hammer Curls', 'Biceps', [], 'Weighted', 'Normal', 'Isolation',
    'Palms facing each other, curl without swinging, control the way down.', 'Forearm and grip strength for grappling.', { reps: '10-12', rest: 45 }),
  ex('Concentration Curls', 'Biceps', [], 'Weighted', 'Normal', 'Isolation',
    'Seated, elbow braced on the inner thigh, curl slow and squeeze at the top.', 'Peak bicep strength for the hook.', { reps: '10-12', rest: 45 }),
  ex('Incline Dumbbell Curls', 'Biceps', [], 'Weighted', 'Normal', 'Isolation',
    'Lie back on an incline, arms hanging, curl without moving the shoulders.', 'Full-range arm strength for a tight clinch.', { reps: '10-12', rest: 45 }),
  ex('Band Curls', 'Biceps', [], 'Band', 'Easy', 'Isolation',
    'Stand on the band, curl the handles to the shoulders against the tension.', 'Arm endurance when the dumbbells are elsewhere.', { reps: '15-20', rest: 30 }),
  ex('Chin-Up Hold', 'Biceps', ['Back'], 'Bodyweight', 'Hard', 'Isolation',
    'Chin over the bar, palms facing you, hold there and keep breathing.', 'Isometric pulling strength for the clinch.', { hold: 20, rest: 60 }),

  // ── Triceps ──────────────────────────────────────────────────────────
  ex('Triceps Dips', 'Triceps', ['Chest', 'Shoulders'], 'Bodyweight', 'Normal', 'Compound',
    'On parallel bars or two chairs, lower until the elbows hit ninety degrees, press to lockout.', 'Lockout strength for every straight punch.', { reps: '8-12' }),
  ex('Close-Grip Push-Ups', 'Triceps', ['Chest'], 'Bodyweight', 'Normal', 'Compound',
    'Hands shoulder-width or closer, elbows brush the ribs on the way down.', 'Triceps snap at the end of the jab.'),
  ex('Dumbbell Skull Crushers', 'Triceps', [], 'Weighted', 'Normal', 'Isolation',
    'Lie back, dumbbells over the face, bend only the elbows to lower them beside the head, extend.', 'Arm extension power for the cross.', { reps: '10-12', rest: 45 }),
  ex('Overhead Dumbbell Extension', 'Triceps', ['Shoulders'], 'Weighted', 'Normal', 'Isolation',
    'One dumbbell held overhead with both hands, lower behind the head, extend to lockout.', 'Overhead lockout for uppercuts and frames.', { reps: '10-12', rest: 45 }),
  ex('Dumbbell Kickbacks', 'Triceps', [], 'Weighted', 'Easy', 'Isolation',
    'Hinge forward, upper arm parallel to the floor, extend the elbow fully and squeeze.', 'Triceps endurance for a snappy jab all night.', { reps: '12-15', rest: 30 }),
  ex('Close-Grip Dumbbell Press', 'Triceps', ['Chest'], 'Weighted', 'Normal', 'Compound',
    'Dumbbells pressed together over the chest, lower to the sternum, press up keeping them touching.', 'Pressing strength with the triceps leading.', { reps: '8-12' }),

  // ── Core ─────────────────────────────────────────────────────────────
  ex('Plank Hold', 'Core', ['Shoulders'], 'Bodyweight', 'Easy', 'Isolation',
    'Forearms down, body in one straight line, squeeze the glutes and breathe.', 'The brace that takes a body shot.', { hold: 30 }),
  ex('Side Plank', 'Core', ['Shoulders'], 'Bodyweight', 'Normal', 'Isolation',
    'On one forearm, hips stacked and lifted, hold, then switch sides.', 'Oblique strength for hooks and for absorbing hooks.', { hold: 30 }),
  ex('Hollow Body Hold', 'Core', [], 'Bodyweight', 'Hard', 'Isolation',
    'On your back, lower back pressed into the floor, shoulders and legs hovering, hold.', 'The tightest possible midsection.', { hold: 30 }),
  ex('Crunches', 'Core', [], 'Bodyweight', 'Easy', 'Isolation',
    'Knees bent, curl the shoulders off the floor, lower slow.', 'Ab endurance for the clinch.', { reps: '15-20', rest: 30 }),
  ex('Sit-Ups', 'Core', ['Quads'], 'Bodyweight', 'Normal', 'Compound',
    'Feet anchored, sit all the way up, lower all the way down with control.', 'Hip flexor and ab strength for kicks and knees.', { reps: '12-20', rest: 30 }),
  ex('Reverse Crunches', 'Core', [], 'Bodyweight', 'Easy', 'Isolation',
    'On your back, knees bent, curl the hips off the floor toward the chest, lower slow.', 'Lower abs for knee strikes.', { reps: '12-15', rest: 30 }),
  ex('Leg Raises', 'Core', [], 'Bodyweight', 'Normal', 'Isolation',
    'Legs straight, raise them to vertical, lower without letting them touch the floor.', 'Lower-ab strength for kicks and takedown defence.', { reps: '10-15', rest: 30 }),
  ex('Flutter Kicks', 'Core', [], 'Bodyweight', 'Normal', 'Isolation',
    'Legs hovering, kick them in small fast scissors, lower back pressed down.', 'Core endurance for a busy fight.', { reps: '20-30', rest: 30 }),
  ex('Russian Twists', 'Core', [], 'Bodyweight', 'Normal', 'Isolation',
    'Seated, lean back, feet up, twist the hands side to side.', 'Rotation power for hooks and elbows.', { reps: '20-30', rest: 30 }),
  ex('V-Ups', 'Core', ['Quads'], 'Bodyweight', 'Hard', 'Compound',
    'Lie flat, lift the legs and shoulders together to touch the toes, lower with control.', 'Explosive core strength for scrambles.', { reps: '10-15', rest: 45 }),
  ex('Mountain Climbers', 'Core', ['Shoulders', 'Quads'], 'Bodyweight', 'Normal', 'Compound',
    'High plank, drive the knees to the chest fast, hips low.', 'Sharpens hip drive and ground movement.', { hold: 30, style: 'Conditioning' }),
  ex('Weighted Russian Twists', 'Core', [], 'Weighted', 'Normal', 'Isolation',
    'Seated with a dumbbell, lean back, twist it side to side touching the floor each way.', 'Loaded rotation for heavier hooks.', { reps: '16-24', rest: 30 }),
  ex('Weighted Sit-Ups', 'Core', [], 'Weighted', 'Normal', 'Compound',
    'Dumbbell held to the chest, sit all the way up, lower slow.', 'Core strength that holds up in the clinch.', { reps: '10-15', rest: 45 }),
  ex('Dumbbell Side Bends', 'Core', [], 'Weighted', 'Easy', 'Isolation',
    'One dumbbell at the side, bend toward it, pull back up with the opposite oblique.', 'Oblique strength for taking body shots.', { reps: '12-15', rest: 30 }),
  ex('Weighted Plank', 'Core', ['Shoulders'], 'Weighted', 'Hard', 'Isolation',
    'A plate or dumbbell across the upper back, hold a perfect plank.', 'A brace that laughs at body shots.', { hold: 30, rest: 45 }),

  // ── Quads ────────────────────────────────────────────────────────────
  ex('Squats', 'Quads', ['Glutes', 'Hamstrings'], 'Bodyweight', 'Easy', 'Compound',
    'Feet shoulder-width, sit the hips back and down until the thighs are parallel, drive up.', 'The base of every stance and every kick.', { reps: '12-20' }),
  ex('Jump Squats', 'Quads', ['Glutes', 'Calves'], 'Bodyweight', 'Normal', 'Compound',
    'Sink to a squat and jump as high as you can, land soft and go again.', 'Explosive leg drive for closing distance.', { reps: '8-12', rest: 45 }),
  ex('Lunges', 'Quads', ['Glutes', 'Hamstrings'], 'Bodyweight', 'Easy', 'Compound',
    'Step forward, back knee toward the floor, push off the front heel to stand.', 'Single-leg strength for footwork.', { reps: '10-12' }),
  ex('Walking Lunges', 'Quads', ['Glutes'], 'Bodyweight', 'Normal', 'Compound',
    'Lunge forward and keep walking, chest tall, knees tracking over the toes.', 'Stance transitions and leg endurance.', { reps: '12-16' }),
  ex('Reverse Lunges', 'Quads', ['Glutes', 'Hamstrings'], 'Bodyweight', 'Easy', 'Compound',
    'Step back into the lunge, front shin vertical, drive through the front heel.', 'The leg drive behind a retreat and counter.', { reps: '10-12' }),
  ex('Split Squats', 'Quads', ['Glutes'], 'Bodyweight', 'Normal', 'Compound',
    'One foot in front, lower straight down until the back knee kisses the floor, drive up.', 'Rooted single-leg strength for kicks and takedown defence.', { reps: '8-12' }),
  ex('Wall Sit', 'Quads', ['Glutes'], 'Bodyweight', 'Easy', 'Isolation',
    'Back flat on the wall, thighs parallel to the floor, hold.', 'Leg endurance for a low stance late in the fight.', { hold: 45 }),
  ex('Pistol Squats', 'Quads', ['Glutes', 'Core'], 'Bodyweight', 'Hard', 'Compound',
    'One leg out in front, sit all the way down on the other, stand without touching down.', 'Elite single-leg strength and balance.', { reps: '4-6', rest: 75 }),
  ex('Step-Ups', 'Quads', ['Glutes'], 'Bodyweight', 'Easy', 'Compound',
    'Step fully onto a box, drive through the top heel, step down under control.', 'Leg drive for pushing off and angling out.', { reps: '10-12' }),
  ex('Goblet Squats', 'Quads', ['Glutes', 'Core'], 'Weighted', 'Normal', 'Compound',
    'Dumbbell held at the chest, squat deep with the elbows inside the knees, drive up.', 'Loaded leg strength for a heavier stance.', { reps: '8-12', rest: 75 }),
  ex('Dumbbell Front Squats', 'Quads', ['Glutes', 'Core'], 'Weighted', 'Normal', 'Compound',
    'Dumbbells racked on the shoulders, chest tall, squat to parallel and drive up.', 'Front-loaded strength that keeps the torso upright under pressure.', { reps: '8-10', rest: 75 }),
  ex('Barbell Back Squats', 'Quads', ['Glutes', 'Hamstrings'], 'Weighted', 'Hard', 'Compound',
    'Bar across the upper back, brace, sit down to parallel, drive the floor away.', 'The heaviest leg strength there is.', { reps: '5-8', rest: 120 }),
  ex('Dumbbell Lunges', 'Quads', ['Glutes'], 'Weighted', 'Normal', 'Compound',
    'Dumbbells at the sides, lunge forward, push off the front heel to return.', 'Loaded single-leg power for footwork.', { reps: '8-12', rest: 60 }),
  ex('Bulgarian Split Squats', 'Quads', ['Glutes', 'Hamstrings'], 'Weighted', 'Hard', 'Compound',
    'Rear foot up on a bench, lower straight down on the front leg, drive up.', 'Single-leg strength that shows up in every kick.', { reps: '6-10', rest: 75 }),
  ex('Dumbbell Step-Ups', 'Quads', ['Glutes'], 'Weighted', 'Normal', 'Compound',
    'Dumbbells at the sides, step fully onto the box, control the way down.', 'Loaded leg drive for explosive entries.', { reps: '8-10', rest: 60 }),

  // ── Hamstrings ───────────────────────────────────────────────────────
  ex('Single-Leg Romanian Deadlift', 'Hamstrings', ['Glutes', 'Core'], 'Bodyweight', 'Normal', 'Compound',
    'Balance on one leg, hinge forward with the other leg reaching back, stand tall.', 'Balance and hamstring strength for checking kicks.', { reps: '8-10' }),
  ex('Nordic Curl Negatives', 'Hamstrings', ['Glutes'], 'Bodyweight', 'Hard', 'Isolation',
    'Ankles anchored, lower the body forward as slowly as you can, catch with the hands.', 'Bulletproof hamstrings for sprint-and-stop footwork.', { reps: '4-6', rest: 90 }),
  ex('Hamstring Walkouts', 'Hamstrings', ['Glutes'], 'Bodyweight', 'Normal', 'Isolation',
    'Glute bridge position, walk the heels out until the legs are nearly straight, walk them back.', 'Hamstring endurance for a bouncing stance.', { reps: '8-10', rest: 45 }),
  ex('Sliding Leg Curls', 'Hamstrings', ['Glutes'], 'Bodyweight', 'Normal', 'Isolation',
    'Heels on a towel or sliders, hips up, pull the heels to the glutes and slide back out.', 'Knee-friendly hamstring strength.', { reps: '10-12', rest: 45 }),
  ex('Romanian Deadlifts', 'Hamstrings', ['Glutes', 'Back'], 'Weighted', 'Normal', 'Compound',
    'Bar at the thighs, push the hips back with a flat back until you feel the hamstrings, stand up.', 'Hip hinge power for every takedown and sprawl.', { reps: '8-10', rest: 90 }),
  ex('Dumbbell Romanian Deadlifts', 'Hamstrings', ['Glutes', 'Back'], 'Weighted', 'Normal', 'Compound',
    'Dumbbells down the front of the thighs, hinge back with a flat back, drive the hips forward to stand.', 'Posterior chain for a rooted, explosive stance.', { reps: '8-12', rest: 75 }),
  ex('Kettlebell Swings', 'Hamstrings', ['Glutes', 'Core'], 'Weighted', 'Normal', 'Compound',
    'Hinge, hike the bell back, snap the hips forward to chest height, let it fall and repeat.', 'Hip snap — the engine of every punch and every kick.', { reps: '12-20', rest: 45, style: 'Power' }),
  ex('Stiff-Leg Deadlifts', 'Hamstrings', ['Glutes', 'Back'], 'Weighted', 'Hard', 'Compound',
    'Legs nearly straight, hinge until the bar is at mid-shin, stand tall with the glutes.', 'Hamstring strength under load.', { reps: '6-10', rest: 90 }),
  ex('Sumo Deadlifts', 'Hamstrings', ['Glutes', 'Quads'], 'Weighted', 'Normal', 'Compound',
    'Wide stance, toes out, hands inside the knees, drive the floor apart and stand.', 'Hip strength for a wide, stable base.', { reps: '6-10', rest: 90 }),

  // ── Glutes ───────────────────────────────────────────────────────────
  ex('Donkey Kicks', 'Glutes', ['Hamstrings'], 'Bodyweight', 'Easy', 'Isolation',
    'On hands and knees, kick one heel to the ceiling with the knee bent, squeeze at the top.', 'Glute activation for kicks and knees.', { reps: '12-15', rest: 30 }),
  ex('Clamshells', 'Glutes', [], 'Bodyweight', 'Easy', 'Isolation',
    'On your side, knees bent and feet together, open the top knee like a clam, lower slow.', 'Hip stability for checking kicks and pivots.', { reps: '15-20', rest: 30 }),
  ex('Frog Pumps', 'Glutes', [], 'Bodyweight', 'Easy', 'Isolation',
    'On your back, soles of the feet together, pump the hips up fast and squeeze.', 'Glute endurance for a bouncy stance.', { reps: '20-30', rest: 30 }),
  ex('Single-Leg Hip Thrusts', 'Glutes', ['Hamstrings'], 'Bodyweight', 'Normal', 'Compound',
    'Shoulders on a bench, one foot down, drive that hip up until the body is level, lower slow.', 'Single-leg hip power for kicks.', { reps: '8-12', rest: 45 }),
  ex('Dumbbell Sumo Squats', 'Glutes', ['Quads'], 'Weighted', 'Normal', 'Compound',
    'Wide stance, dumbbell hanging between the legs, squat deep and drive up through the heels.', 'Hip strength for a wide base.', { reps: '10-12', rest: 60 }),
  ex('Dumbbell Hip Thrusts', 'Glutes', ['Hamstrings'], 'Weighted', 'Normal', 'Compound',
    'Shoulders on a bench, dumbbell on the hips, drive up until the body is level, squeeze.', 'The hip drive behind every knee strike.', { reps: '10-12', rest: 60 }),
  ex('Kettlebell Deadlifts', 'Glutes', ['Hamstrings', 'Back'], 'Weighted', 'Easy', 'Compound',
    'Bell between the feet, hinge with a flat back, stand tall and squeeze the glutes.', 'A safe first hinge for hip power.', { reps: '10-12', rest: 60 }),
  ex('Weighted Step-Ups', 'Glutes', ['Quads'], 'Weighted', 'Normal', 'Compound',
    'Dumbbells at the sides, step onto a high box driving through the heel, control the descent.', 'Glute drive for pushing off the back foot.', { reps: '8-10', rest: 60 }),
  ex('Banded Glute Bridges', 'Glutes', ['Hamstrings'], 'Band', 'Easy', 'Isolation',
    'Band above the knees, drive the hips up while pushing the knees out, squeeze.', 'Glute activation before any leg day.', { reps: '15-20', rest: 30 }),
  ex('Band Lateral Walks', 'Glutes', [], 'Band', 'Easy', 'Isolation',
    'Band above the knees, quarter squat, step sideways against the band, then back.', 'Hip stability for lateral footwork.', { reps: '10-12', rest: 30 }),

  // ── Calves ───────────────────────────────────────────────────────────
  ex('Dumbbell Calf Raises', 'Calves', [], 'Weighted', 'Normal', 'Isolation',
    'Dumbbells at the sides, rise onto the toes, pause, lower slow.', 'Calf strength for staying on the balls of the feet.', { reps: '12-20', rest: 30 }),

  // ── Full Body ────────────────────────────────────────────────────────
  ex('Burpees', 'Full Body', ['Chest', 'Quads', 'Core'], 'Bodyweight', 'Normal', 'Compound',
    'Drop to the floor, chest down, pop up and jump. Every rep from the top.', 'Builds the get-up-and-go engine for scrambles.', { reps: '8-12', rest: 45, style: 'Conditioning' }),
  ex('Jumping Jacks', 'Full Body', ['Shoulders', 'Calves'], 'Bodyweight', 'Easy', 'Compound',
    'Stay light on the feet and keep a steady rhythm.', 'Warms the shoulders and keeps the heart rate up.', { hold: 40, style: 'Conditioning' }),
  ex('High Knees', 'Full Body', ['Quads', 'Core'], 'Bodyweight', 'Normal', 'Compound',
    'Pump the arms and drive the knees to hip height.', 'Trains footwork cadence and endurance.', { hold: 30, style: 'Conditioning' }),
  ex('Sprawls', 'Full Body', ['Quads', 'Chest'], 'Bodyweight', 'Normal', 'Compound',
    'Shoot the hips back and down to the floor, pop back up to the stance.', 'The takedown defence, repeated until it is a reflex.', { reps: '8-12', rest: 45, style: 'Conditioning' }),
  ex('Squat Thrusts', 'Full Body', ['Quads', 'Core'], 'Bodyweight', 'Normal', 'Compound',
    'Hands down, kick the feet back to a plank, jump them back in, stand.', 'Ground-to-feet speed.', { reps: '10-15', rest: 45, style: 'Conditioning' }),
  ex('Thrusters', 'Full Body', ['Quads', 'Shoulders'], 'Weighted', 'Hard', 'Compound',
    'Dumbbells at the shoulders, squat, and drive straight into an overhead press.', 'Legs-to-arms power transfer — the whole punch.', { reps: '8-10', rest: 75, style: 'Power' }),
  ex('Clean and Press', 'Full Body', ['Hamstrings', 'Shoulders'], 'Weighted', 'Hard', 'Compound',
    'Pull the dumbbells from the floor to the shoulders in one move, then press overhead.', 'Explosive full-body power.', { reps: '6-8', rest: 90, style: 'Power' }),
  ex('Farmer Carries', 'Full Body', ['Core', 'Back'], 'Weighted', 'Normal', 'Compound',
    'Heavy dumbbells at the sides, walk tall with the shoulders back.', 'Grip and core for the clinch.', { hold: 40, rest: 60, style: 'Conditioning' }),
  ex('Man Makers', 'Full Body', ['Chest', 'Back', 'Quads'], 'Weighted', 'Hard', 'Compound',
    'Push-up on the dumbbells, row each side, jump in, clean and press overhead.', 'The whole fight in one rep.', { reps: '5-8', rest: 90, style: 'Conditioning' }),
  ex('Dumbbell Snatch', 'Full Body', ['Hamstrings', 'Shoulders'], 'Weighted', 'Hard', 'Compound',
    'One dumbbell between the feet, hinge, and pull it overhead in one explosive move, alternate arms.', 'Hip snap into an overhead lockout.', { reps: '6-8', rest: 75, style: 'Power' }),
];
