/**
 * Image optimization — resizes large banners to display-appropriate sizes and
 * generates WebP versions for the priority asset folders. Uses ImageMagick
 * (`magick`), which is available in this environment (sharp is not).
 *
 * For each readable image it:
 *   1. Writes a resized .webp sibling (primary asset served via SafeImage).
 *   2. Downscales the .png/.jpg fallback in place (only if it ends up smaller).
 *
 * Originals that are unreadable/corrupt are skipped (never registered as WebP),
 * so SafeImage never requests a .webp that does not exist.
 *
 * It also writes data/webpManifest.js listing every generated WebP path so
 * SafeImage knows exactly which WebP files exist.
 *
 * Usage: npm run optimize:images
 */

import { readdirSync, statSync, existsSync, renameSync, unlinkSync, writeFileSync } from 'fs';
import { join, extname, basename } from 'path';
import { execFileSync } from 'child_process';

const ROOT = process.cwd();
const PUBLIC_DIR = join(ROOT, 'public');

// Per-folder max box size (longest side). Downscale only — never upscale.
const DIR_TARGETS = {
  'Hub': 960,
  'banners': 800,
  'banners/arcade': 800,
  'discipline-cards': 540,
  'rewards': 400,
  'fit-mode': 600,
  'fit-mode/body-maps': 600,
  'training-arcade/stage-banners': 800,
  'training-arcade/results': 800,
  'training-arcade/rewards': 500,
};

const QUALITY = 85;
const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg']);

function isReadable(p) {
  try {
    execFileSync('identify', ['-quiet', p + '[0]'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function fmt(bytes) {
  return (bytes / 1024).toFixed(0) + ' KB';
}

const generatedWebp = [];

for (const [dir, box] of Object.entries(DIR_TARGETS)) {
  const fullDir = join(PUBLIC_DIR, dir);
  if (!existsSync(fullDir)) continue;

  console.log(`\n[${dir}] (max ${box}px)`);

  for (const file of readdirSync(fullDir)) {
    const ext = extname(file).toLowerCase();
    if (!IMAGE_EXTENSIONS.has(ext)) continue;

    const input = join(fullDir, file);
    const stat = statSync(input);
    if (!stat.isFile() || stat.size === 0) continue;

    if (!isReadable(input)) {
      console.log(`  [SKIP] ${file} (unreadable/corrupt — left as-is, no WebP)`);
      continue;
    }

    const base = basename(file, ext);
    const geometry = `${box}x${box}>`; // fit within box, shrink-only

    // 1. WebP sibling
    const webpOut = join(fullDir, base + '.webp');
    try {
      execFileSync('magick', [input, '-resize', geometry, '-strip', '-quality', String(QUALITY), webpOut]);
      const webpSize = statSync(webpOut).size;
      const savings = Math.round((1 - webpSize / stat.size) * 100);
      console.log(`  [WEBP] ${base}.webp  ${fmt(stat.size)} -> ${fmt(webpSize)} (${savings}% smaller)`);
      generatedWebp.push(`/${dir}/${base}.webp`);
    } catch (err) {
      console.error(`  [FAIL webp] ${file}: ${err.message}`);
      continue;
    }

    // 2. Downscaled PNG/JPG fallback (replace only if smaller)
    const tmp = join(fullDir, base + '.__opt__' + ext);
    try {
      execFileSync('magick', [input, '-resize', geometry, '-strip', tmp]);
      if (statSync(tmp).size < stat.size) {
        renameSync(tmp, input);
        console.log(`  [PNG ] ${file}   ${fmt(stat.size)} -> ${fmt(statSync(input).size)} (fallback resized)`);
      } else {
        unlinkSync(tmp);
      }
    } catch (err) {
      if (existsSync(tmp)) unlinkSync(tmp);
      console.error(`  [FAIL png] ${file}: ${err.message}`);
    }
  }
}

generatedWebp.sort();
const manifestPath = join(ROOT, 'components', 'training-mode', 'data', 'webpManifest.js');
writeFileSync(
  manifestPath,
  '// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.\n' +
  '// Lists public-root-relative paths of WebP files that actually exist on disk,\n' +
  '// so SafeImage only ever requests a .webp that is present (no 404s).\n' +
  'export const WEBP_FILES = [\n' +
  generatedWebp.map((p) => `  '${p}',`).join('\n') +
  '\n];\n'
);

console.log(`\n[Done] Generated ${generatedWebp.length} WebP files. Manifest -> ${manifestPath}\n`);
