export const PRACTICE_DISCIPLINES = ['Boxing', 'Kickboxing', 'Muay Thai', 'MMA'];
export const PRACTICE_CATEGORIES = ['Strikes', 'Defense', 'Footwork'];

// Each technique: discipline, category, name, description, level, duration,
// videoUrl (blank until videos are added), cues, mistakes, next, locked
export const TECHNIQUES = [
  // ── Boxing / Strikes ──────────────────────────────────────────────────────
  {
    discipline: 'Boxing', category: 'Strikes', name: 'Jab',
    description: 'Straight lead-hand punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Hands high', 'Step with the jab', 'Return to guard'],
    mistakes: ['Dropping the rear hand', 'Reaching too far', 'Chin up'],
    next: 'Cross', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Strikes', name: 'Cross',
    description: 'Rear-hand power punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Rotate the hip', 'Drive off the back foot', 'Tuck the chin'],
    mistakes: ['Telegraphing with the shoulder', 'Leaning forward', 'Leaving guard open'],
    next: 'Lead Hook', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Strikes', name: 'Lead Hook',
    description: 'Short-range angle punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot on the lead foot', 'Elbow at shoulder height', 'Snap and return'],
    mistakes: ['Arm swinging wide', 'Dropping the rear hand', 'Standing upright'],
    next: 'Rear Hook', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Strikes', name: 'Rear Hook',
    description: 'Rear-side hook punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Rotate the rear hip', 'Elbow parallel to floor', 'Return to guard fast'],
    mistakes: ['Over-rotating', 'Leaving the chin exposed', 'Looping the arm'],
    next: 'Lead Uppercut', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Strikes', name: 'Lead Uppercut',
    description: 'Close-range rising punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Dip the lead shoulder', 'Drive upward with the legs', 'Palm facing you'],
    mistakes: ['Telegraphing the dip', 'Swinging wide', 'Dropping the rear guard'],
    next: 'Rear Uppercut', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Strikes', name: 'Rear Uppercut',
    description: 'Rear-side rising punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot on the rear foot', 'Use leg drive', 'Stay compact'],
    mistakes: ['Winding up too wide', 'Leaning into it', 'Forgetting the guard'],
    next: 'Overhand', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Strikes', name: 'Overhand',
    description: 'Arcing power shot',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Loop over the guard', 'Come in at an angle', 'Commit weight forward'],
    mistakes: ['Throwing it too wide', 'No head movement', 'Slow return'],
    next: 'Body Jab', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Strikes', name: 'Body Jab',
    description: 'Lead hand body shot',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Bend the knees to level change', 'Aim at the liver or solar plexus', 'Return quickly'],
    mistakes: ['Bending at the waist', 'Slapping instead of jabbing', 'Not protecting the head'],
    next: 'Body Cross', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Strikes', name: 'Body Cross',
    description: 'Rear hand body shot',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Rotate and dip', 'Target the liver', 'Stay explosive on the return'],
    mistakes: ['Telegraphing with a big dip', 'Leaving the head exposed', 'Punching down instead of through'],
    next: 'Jab', locked: true,
  },

  // ── Boxing / Defense ──────────────────────────────────────────────────────
  {
    discipline: 'Boxing', category: 'Defense', name: 'Slip Outside',
    description: 'Dodge outside the straight punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Small bend at the waist', 'Head moves offline', 'Return to center fast'],
    mistakes: ['Moving too wide', 'Dropping hands', 'Slipping late'],
    next: 'Slip Inside', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Defense', name: 'Slip Inside',
    description: 'Dodge inside the straight punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Dip to the inside angle', 'Eyes stay on opponent', 'Hands stay up'],
    mistakes: ['Over-rotating', 'Going too deep', 'Forgetting the counter'],
    next: 'Bob and Weave', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Defense', name: 'Bob and Weave',
    description: 'Roll under hooks and power shots',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['U-shaped movement', 'Bend the knees not the back', 'Explode back up'],
    mistakes: ['Too slow on the rise', 'Bending at waist only', 'Hands dropping'],
    next: 'Parry', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Defense', name: 'Parry',
    description: 'Redirect an incoming punch with the palm',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Small tap with the rear hand', 'Redirect not block', 'Stay relaxed'],
    mistakes: ['Reaching out too far', 'Over-committing', 'Parrying too early'],
    next: 'Slip Outside', locked: true,
  },

  // ── Boxing / Footwork ─────────────────────────────────────────────────────
  {
    discipline: 'Boxing', category: 'Footwork', name: 'Step and Jab',
    description: 'Lead foot step with simultaneous jab',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Step and punch at the same time', 'Land balanced', 'Return guard on the way back'],
    mistakes: ['Stepping before punching', 'Overstepping', 'Flat-footed landing'],
    next: 'Lateral Step', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Footwork', name: 'Lateral Step',
    description: 'Side-to-side evasive movement',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Step-drag pattern', 'Stay on the balls of your feet', 'Keep stance width'],
    mistakes: ['Crossing the feet', 'Standing up too tall', 'Moving too slow'],
    next: 'Pivot', locked: true,
  },
  {
    discipline: 'Boxing', category: 'Footwork', name: 'Pivot',
    description: 'Rotate off the lead foot to create angles',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot on the ball of the lead foot', 'Rear foot follows', 'End in stance'],
    mistakes: ['Pivoting on the heel', 'Losing balance', 'Not exiting to an angle'],
    next: 'Step and Jab', locked: true,
  },

  // ── Kickboxing / Strikes ───────────────────────────────────────────────────
  // Order: Jab, Lead Teep, Cross, Rear Teep, Lead Hook, Switch Kick,
  // Rear Hook, Rear Roundhouse, Lead Uppercut, Lead Knee, Rear Uppercut,
  // Rear Knee, Lead Side Kick, Rear Side Kick, Low Kick, Check
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Jab',
    description: 'Straight lead-hand punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Hands high', 'Step with the jab', 'Return to guard'],
    mistakes: ['Dropping the rear hand', 'Reaching too far', 'Chin up'],
    next: 'Lead Teep', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Lead Teep',
    description: 'Lead-leg front push kick for range control',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Chamber the knee first', 'Push through with the heel', 'Return the foot fast'],
    mistakes: ['Skipping the chamber', 'Pushing too low', 'Landing off-balance'],
    next: 'Cross', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Cross',
    description: 'Rear-hand power punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Rotate the hip', 'Drive off the back foot', 'Tuck the chin'],
    mistakes: ['Telegraphing with the shoulder', 'Leaning forward', 'Leaving guard open'],
    next: 'Rear Teep', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Rear Teep',
    description: 'Rear-leg front push kick with power',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Step in slightly', 'Drive the hip through', 'Land back in stance'],
    mistakes: ['Telegraphing with a lean', 'Locking the knee', 'Kicking too high'],
    next: 'Lead Hook', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Lead Hook',
    description: 'Short-range angle punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot on the lead foot', 'Elbow at shoulder height', 'Snap and return'],
    mistakes: ['Arm swinging wide', 'Dropping the rear hand', 'Standing upright'],
    next: 'Switch Kick', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Switch Kick',
    description: 'Switch stance to disguise rear kick',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Small hop to switch', 'Disguise the switch', 'Kick immediately after switch'],
    mistakes: ['Big telegraphing hop', 'Slow switch', 'Landing wrong stance after'],
    next: 'Rear Hook', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Rear Hook',
    description: 'Rear-side hook punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Rotate the rear hip', 'Elbow parallel to floor', 'Return to guard fast'],
    mistakes: ['Over-rotating', 'Leaving the chin exposed', 'Looping the arm'],
    next: 'Rear Roundhouse Kick', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Rear Roundhouse Kick',
    description: 'Rear-leg power kick to body or head',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Load the hip back', 'Pivot hard on the base foot', 'Strike with the shin'],
    mistakes: ['No hip rotation', 'Kicking with the foot', 'Slow return'],
    next: 'Lead Uppercut', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Lead Uppercut',
    description: 'Close-range rising punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Dip the lead shoulder', 'Drive upward with the legs', 'Palm facing you'],
    mistakes: ['Telegraphing the dip', 'Swinging wide', 'Dropping the rear guard'],
    next: 'Lead Knee', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Lead Knee',
    description: 'Lead-leg knee strike at close range',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Drive hip forward', 'Pull opponent in if possible', 'Strike with the tip of the knee'],
    mistakes: ['No hip engagement', 'Kneeing with the thigh', 'Losing balance on impact'],
    next: 'Rear Uppercut', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Rear Uppercut',
    description: 'Rear-side rising punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot on the rear foot', 'Use leg drive', 'Stay compact'],
    mistakes: ['Winding up too wide', 'Leaning into it', 'Forgetting the guard'],
    next: 'Rear Knee', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Rear Knee',
    description: 'Rear-leg knee strike with power',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Step in to close distance', 'Drive the hip through', 'Target the body'],
    mistakes: ['No hip drive', 'Staying too far away', 'Losing guard on entry'],
    next: 'Lead Side Kick', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Lead Side Kick',
    description: 'Lateral thrust kick from the lead leg',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Chamber at the hip', 'Thrust heel-first', 'Lean away for power'],
    mistakes: ['Kicking with the toe', 'Not chambering', 'No lean for range'],
    next: 'Rear Side Kick', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Rear Side Kick',
    description: 'Lateral thrust kick from the rear leg',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Turn the hip over', 'Drive through the heel', 'Keep guard hand high'],
    mistakes: ['Kicking with the ball of the foot', 'Not turning the hip', 'Slow recovery'],
    next: 'Low Kick', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Low Kick',
    description: 'Rear roundhouse to the lead leg',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot the base foot', 'Strike with the shin', 'Return to stance fast'],
    mistakes: ['Kicking with the foot', 'No pivot', 'Kicking too high'],
    next: 'Check', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Strikes', name: 'Check',
    description: 'Shin block against incoming leg kicks',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Raise the knee and tilt', 'Meet the incoming shin', 'Keep hands high'],
    mistakes: ['Late reaction', 'Checking with the ankle', 'Dropping the guard'],
    next: 'Jab', locked: true,
  },

  // ── Kickboxing / Defense ──────────────────────────────────────────────────
  {
    discipline: 'Kickboxing', category: 'Defense', name: 'Low Kick Check',
    description: 'Lift the shin to block incoming leg kicks',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Lift the knee', 'Turn the shin out', 'Keep hands up'],
    mistakes: ['Checking too late', 'Dropping the guard', 'Checking with the foot'],
    next: 'Catch and Return', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Defense', name: 'Catch and Return',
    description: 'Catch a kick and counter-attack',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Scoop the kick with both arms', 'Step in to unbalance', 'Return immediately'],
    mistakes: ['Catching only with one arm', 'Hesitating on the return', 'Not stepping in'],
    next: 'Low Kick Check', locked: true,
  },

  // ── Kickboxing / Footwork ─────────────────────────────────────────────────
  {
    discipline: 'Kickboxing', category: 'Footwork', name: 'Kick Exit',
    description: 'Exit to angle after landing a kick',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Plant the kicking leg at an angle', 'Exit away from counter', 'Reset in stance'],
    mistakes: ['Stepping straight back', 'Planting too close', 'Standing still after kick'],
    next: 'Kick Entry', locked: true,
  },
  {
    discipline: 'Kickboxing', category: 'Footwork', name: 'Kick Entry',
    description: 'Close distance to set up kicks',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Feint to close distance', 'Keep hands up on the way in', 'Strike on the step'],
    mistakes: ['Running in straight', 'Dropping guard', 'Kicking from too far'],
    next: 'Kick Exit', locked: true,
  },

  // ── Muay Thai / Strikes ───────────────────────────────────────────────────
  // Order: Jab, Lead Teep, Cross, Rear Teep, Lead Hook, Lead Horizontal Elbow,
  // Rear Hook, Rear Roundhouse Kick, Lead Uppercut, Lead Knee, Rear Uppercut,
  // Rear Knee, Lead Spear Elbow, Rear Spear Elbow, Check, Clinch Entry
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Jab',
    description: 'Straight lead-hand punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Hands high', 'Step with the jab', 'Return to guard'],
    mistakes: ['Dropping the rear hand', 'Reaching too far', 'Chin up'],
    next: 'Lead Teep', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Lead Teep',
    description: 'Muay Thai front push kick for range',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Drive the hip forward', 'Push with the ball of the foot', 'Use it as a range tool'],
    mistakes: ['Kicking too low', 'No hip drive', 'Telegraphing'],
    next: 'Cross', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Cross',
    description: 'Rear-hand power punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Rotate the hip', 'Drive off the back foot', 'Tuck the chin'],
    mistakes: ['Telegraphing with the shoulder', 'Leaning forward', 'Leaving guard open'],
    next: 'Rear Teep', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Rear Teep',
    description: 'Rear-leg push kick with power',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Step in slightly', 'Drive the hip through', 'Land back in stance'],
    mistakes: ['Telegraphing with a lean', 'Locking the knee', 'Kicking too high'],
    next: 'Lead Hook', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Lead Hook',
    description: 'Short-range angle punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot on the lead foot', 'Elbow at shoulder height', 'Snap and return'],
    mistakes: ['Arm swinging wide', 'Dropping the rear hand', 'Standing upright'],
    next: 'Lead Horizontal Elbow', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Lead Horizontal Elbow',
    description: 'Horizontal slashing elbow from the lead side',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Close the distance first', 'Strike with the tip of the elbow', 'Swing through the target'],
    mistakes: ['Too much wind-up', 'Striking with the forearm', 'Leaving chin exposed'],
    next: 'Rear Hook', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Rear Hook',
    description: 'Rear-side hook punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Rotate the rear hip', 'Elbow parallel to floor', 'Return to guard fast'],
    mistakes: ['Over-rotating', 'Leaving the chin exposed', 'Looping the arm'],
    next: 'Rear Roundhouse Kick', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Rear Roundhouse Kick',
    description: 'Full-rotation shin kick with power',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Full hip rotation', 'Strike with the shin', 'Swing the arm for power'],
    mistakes: ['Kicking with the foot', 'No pivot', 'Forgetting the follow-through'],
    next: 'Lead Uppercut', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Lead Uppercut',
    description: 'Close-range rising punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Dip the lead shoulder', 'Drive upward with the legs', 'Palm facing you'],
    mistakes: ['Telegraphing the dip', 'Swinging wide', 'Dropping the rear guard'],
    next: 'Lead Knee', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Lead Knee',
    description: 'Straight or diagonal knee from the lead leg',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Pull the opponent in', 'Drive the hip forward', 'Target the body or head'],
    mistakes: ['No hip drive', 'Kneeing with the kneecap', 'Losing the clinch grip'],
    next: 'Rear Uppercut', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Rear Uppercut',
    description: 'Rear-side rising punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot on the rear foot', 'Use leg drive', 'Stay compact'],
    mistakes: ['Winding up too wide', 'Leaning into it', 'Forgetting the guard'],
    next: 'Rear Knee', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Rear Knee',
    description: 'Rear-leg knee strike with full hip drive',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Step in to close distance', 'Drive the hip through', 'Target the body'],
    mistakes: ['No hip drive', 'Staying too far away', 'Losing guard on entry'],
    next: 'Lead Spear Elbow', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Lead Spear Elbow',
    description: 'Downward spearing elbow from the lead side',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Raise the elbow high', 'Drive downward through the target', 'Use in clinch range'],
    mistakes: ['Missing the angle', 'Not closing distance', 'Telegraphing the raise'],
    next: 'Rear Spear Elbow', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Rear Spear Elbow',
    description: 'Downward spearing elbow from the rear side',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Step in with the rear foot', 'Drive the elbow tip downward', 'Follow through completely'],
    mistakes: ['Too far away', 'Hitting with the forearm', 'No weight shift'],
    next: 'Check', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Check',
    description: 'Shin-to-shin block against kicks',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Raise the knee and tilt', 'Meet the incoming shin', 'Keep hands high'],
    mistakes: ['Late reaction', 'Checking with the ankle', 'Dropping the guard'],
    next: 'Clinch Entry', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Strikes', name: 'Clinch Entry',
    description: 'Enter the clinch to control and strike',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Step to inside position', 'Control the neck', 'Strike from the clinch'],
    mistakes: ['Entering with no guard', 'Grabbing the arms only', 'Standing too upright'],
    next: 'Jab', locked: true,
  },

  // ── Muay Thai / Defense ───────────────────────────────────────────────────
  {
    discipline: 'Muay Thai', category: 'Defense', name: 'Teep Defense',
    description: 'Catch or block incoming teeps',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Step offline', 'Catch with both hands', 'Counter immediately'],
    mistakes: ['Standing flat-footed', 'One-hand catch', 'No counter'],
    next: 'Elbow Cover', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Defense', name: 'Elbow Cover',
    description: 'Protect the head from elbow strikes',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Tuck the elbow to cover', 'Move offline', 'Return fire'],
    mistakes: ['Standing still', 'Covering with the hand only', 'Not countering'],
    next: 'Teep Defense', locked: true,
  },

  // ── Muay Thai / Footwork ──────────────────────────────────────────────────
  {
    discipline: 'Muay Thai', category: 'Footwork', name: 'Angle Exit',
    description: 'Exit to the side after striking',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Step to the outside angle', 'Pivot away', 'Reset with hands up'],
    mistakes: ['Stepping back in a line', 'Pausing after exit', 'Losing guard'],
    next: 'Clinch Walk', locked: true,
  },
  {
    discipline: 'Muay Thai', category: 'Footwork', name: 'Clinch Walk',
    description: 'Footwork inside the clinch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Small steps to stay balanced', 'Control the position', 'Set up knees'],
    mistakes: ['Big steps that lose balance', 'Letting go of clinch control', 'Flat feet'],
    next: 'Angle Exit', locked: true,
  },

  // ── MMA / Strikes ─────────────────────────────────────────────────────────
  // Order: Jab, Lead Teep, Cross, Rear Teep, Lead Hook, Low Kick,
  // Rear Hook, Rear Roundhouse Kick, Lead Uppercut, Lead Knee, Rear Uppercut,
  // Rear Knee, Overhand, Sprawl, Level Change, Basic Shoot Entry,
  // Ground-and-Pound Posture
  {
    discipline: 'MMA', category: 'Strikes', name: 'Jab',
    description: 'Straight lead-hand punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Hands high', 'Step with the jab', 'Return to guard'],
    mistakes: ['Dropping the rear hand', 'Reaching too far', 'Chin up'],
    next: 'Lead Teep', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Lead Teep',
    description: 'Lead-leg push kick for distance management',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Chamber the knee', 'Push through with the heel', 'Return to stance quickly'],
    mistakes: ['No chamber', 'Leaning back too far', 'Slow recovery'],
    next: 'Cross', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Cross',
    description: 'Rear-hand straight punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Rotate hip and shoulder', 'Drive off the rear foot', 'Protect the chin'],
    mistakes: ['Telegraphing', 'No rotation', 'Forgetting rear hand after'],
    next: 'Rear Teep', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Rear Teep',
    description: 'Rear-leg push kick with stopping power',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Step in slightly', 'Drive the hip through', 'Land back in stance'],
    mistakes: ['Telegraphing with a lean', 'Locking the knee', 'Kicking too high'],
    next: 'Lead Hook', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Lead Hook',
    description: 'Short-range angle punch',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot on the lead foot', 'Elbow at shoulder height', 'Snap and return'],
    mistakes: ['Arm swinging wide', 'Dropping the rear hand', 'Standing upright'],
    next: 'Low Kick', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Low Kick',
    description: 'Rear roundhouse to the lead leg',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot the base foot', 'Strike with the shin', 'Return to stance fast'],
    mistakes: ['Kicking with the foot', 'No pivot', 'Kicking too high'],
    next: 'Rear Hook', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Rear Hook',
    description: 'Rear-side hook punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Rotate the rear hip', 'Elbow parallel to floor', 'Return to guard fast'],
    mistakes: ['Over-rotating', 'Leaving the chin exposed', 'Looping the arm'],
    next: 'Rear Roundhouse Kick', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Rear Roundhouse Kick',
    description: 'Full-rotation shin kick to body or head',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Full hip rotation', 'Strike with the shin', 'Swing the arm for power'],
    mistakes: ['Kicking with the foot', 'No pivot', 'Forgetting the follow-through'],
    next: 'Lead Uppercut', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Lead Uppercut',
    description: 'Close-range rising punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Dip the lead shoulder', 'Drive upward with the legs', 'Palm facing you'],
    mistakes: ['Telegraphing the dip', 'Swinging wide', 'Dropping the rear guard'],
    next: 'Lead Knee', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Lead Knee',
    description: 'Lead-leg knee strike at close range',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Drive hip forward', 'Pull opponent in if possible', 'Strike with the tip of the knee'],
    mistakes: ['No hip engagement', 'Kneeing with the thigh', 'Losing balance on impact'],
    next: 'Rear Uppercut', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Rear Uppercut',
    description: 'Rear-side rising punch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Pivot on the rear foot', 'Use leg drive', 'Stay compact'],
    mistakes: ['Winding up too wide', 'Leaning into it', 'Forgetting the guard'],
    next: 'Rear Knee', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Rear Knee',
    description: 'Rear-leg knee strike with full hip drive',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Step in to close distance', 'Drive the hip through', 'Target the body'],
    mistakes: ['No hip drive', 'Staying too far away', 'Losing guard on entry'],
    next: 'Overhand', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Overhand',
    description: 'Arcing rear-hand power shot',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Angle in', 'Loop over the guard', 'Commit weight'],
    mistakes: ['Telegraphing with shoulder', 'Too wide arc', 'Slow return'],
    next: 'Sprawl', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Sprawl',
    description: 'Defensive movement against takedowns',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Shoot the hips back and down', 'Flatten the opponent', 'Crossface or back-take'],
    mistakes: ['Jumping back instead of sprawling', 'Not driving the hips', 'Losing the head position'],
    next: 'Level Change', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Level Change',
    description: 'Drop the level to set up takedowns',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Bend the knees not the back', 'Keep head off center', 'Drive through on entry'],
    mistakes: ['Telegraphing with a dip', 'Ducking the head only', 'Slow penetration step'],
    next: 'Basic Shoot Entry', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Basic Shoot Entry',
    description: 'Penetration step into a takedown attempt',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Drop level first', 'Penetration step deep', 'Head on the inside'],
    mistakes: ['Reaching without stepping', 'Head down on entry', 'No level change before shoot'],
    next: 'Ground-and-Pound Posture', locked: true,
  },
  {
    discipline: 'MMA', category: 'Strikes', name: 'Ground-and-Pound Posture',
    description: 'Maintain posture and strike from top position',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Posture up with hips forward', 'Use short strikes', 'Control the position first'],
    mistakes: ['Leaning too far forward', 'Wild swings from top', 'Letting opponent control posture'],
    next: 'Jab', locked: true,
  },

  // ── MMA / Defense ─────────────────────────────────────────────────────────
  {
    discipline: 'MMA', category: 'Defense', name: 'Sprawl Defense',
    description: 'Counter the double-leg takedown',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Hips back and down', 'Crossface immediately', 'Stay heavy on top'],
    mistakes: ['Sprawling too late', 'Letting the hips get under', 'No crossface'],
    next: 'Clinch Defense', locked: true,
  },
  {
    discipline: 'MMA', category: 'Defense', name: 'Clinch Defense',
    description: 'Defend and exit the dirty boxing clinch',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Frame with the forearm', 'Create space', 'Exit to an angle'],
    mistakes: ['Pulling away without framing', 'Staying in front', 'Letting go of position control'],
    next: 'Sprawl Defense', locked: true,
  },

  // ── MMA / Footwork ────────────────────────────────────────────────────────
  {
    discipline: 'MMA', category: 'Footwork', name: 'Cage Awareness',
    description: 'Move with awareness of the cage perimeter',
    level: 'Beginner', duration: '20–30 sec', videoUrl: '',
    cues: ['Circle away from the cage', 'Never back straight in', 'Use lateral movement'],
    mistakes: ['Stepping back in a straight line', 'Ignoring cage position', 'Flat feet'],
    next: 'Level Change Entry', locked: true,
  },
  {
    discipline: 'MMA', category: 'Footwork', name: 'Level Change Entry',
    description: 'Use footwork to close for grappling',
    level: 'Intermediate', duration: '20–30 sec', videoUrl: '',
    cues: ['Feint high to drop low', 'Penetration step on entry', 'Head offline on entry'],
    mistakes: ['Ducking straight in', 'No level change deception', 'Chin down but head straight'],
    next: 'Cage Awareness', locked: true,
  },
];
